language: minimal

os:
  # - osx
  - windows
  - linux

before_install:
  - export PATH=$HOME/.deno/bin:$PATH

install:
  - curl -L https://deno.land/x/install/install.py | python

script:
  - deno -v
  - deno test/index.spec.ts
