language: node_js
dist: trusty
node_js:
  - v8
  - v10
  - v11
before_script:
  - npm install -g npm@latest coveralls codecov --quiet
script:
  - npm cit
after_success:
  - 'cat ./coverage/lcov.info | coveralls'
  - 'cat ./coverage/lcov.info | codecov'
