max_jobs: 4

environment:
  CODECOV_TOKEN:
    secure: 5SygvlgfTewBB3CTmBxUfQ==
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm
  - node --version
  - npm --version
  - npm install

# Build
build_script:
  - npm run build

# Post-install test scripts
test_script:
  - npm test

# Submit coverage reports
after_test:
  - npm run coveralls
  - npm run codecov

# Don't actually build
build: off
